// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WakeProWebApi.Contexts;

#nullable disable

namespace WakeProWebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WakeProWebApi.Models.LearningPattern", b =>
                {
                    b.Property<int>("LearningPatternId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LearningPatternId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LearningPatternId");

                    b.ToTable("LearningPatterns");

                    b.HasData(
                        new
                        {
                            LearningPatternId = 1,
                            Name = "Basic Features"
                        },
                        new
                        {
                            LearningPatternId = 2,
                            Name = "Kicker"
                        },
                        new
                        {
                            LearningPatternId = 3,
                            Name = "Degrees/Spins"
                        });
                });

            modelBuilder.Entity("WakeProWebApi.Models.PatternTrickMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<int>("PatternId")
                        .HasColumnType("int");

                    b.Property<int>("TrickId")
                        .HasColumnType("int");

                    b.HasKey("MappingId");

                    b.ToTable("PatternTrickMappings");

                    b.HasData(
                        new
                        {
                            MappingId = 1,
                            PatternId = 1,
                            TrickId = 1
                        },
                        new
                        {
                            MappingId = 2,
                            PatternId = 1,
                            TrickId = 2
                        },
                        new
                        {
                            MappingId = 3,
                            PatternId = 2,
                            TrickId = 2
                        },
                        new
                        {
                            MappingId = 4,
                            PatternId = 2,
                            TrickId = 3
                        },
                        new
                        {
                            MappingId = 5,
                            PatternId = 2,
                            TrickId = 4
                        });
                });

            modelBuilder.Entity("WakeProWebApi.Models.Trick", b =>
                {
                    b.Property<int>("TrickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrickId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrickId");

                    b.ToTable("Tricks");

                    b.HasData(
                        new
                        {
                            TrickId = 1,
                            Description = "Trick 1 description",
                            DifficultyLevel = 1,
                            Name = "Trick1",
                            VideoUrl = "https://www.example.com/trick1"
                        },
                        new
                        {
                            TrickId = 2,
                            Description = "Trick 2 description",
                            DifficultyLevel = 1,
                            Name = "Trick2",
                            VideoUrl = "https://www.example.com/trick2"
                        },
                        new
                        {
                            TrickId = 3,
                            Description = "Trick 3 description",
                            DifficultyLevel = 2,
                            Name = "Trick3",
                            VideoUrl = "https://www.example.com/trick3"
                        },
                        new
                        {
                            TrickId = 4,
                            Description = "Trick 4 description",
                            DifficultyLevel = 2,
                            Name = "Trick4",
                            VideoUrl = "https://www.example.com/trick4"
                        },
                        new
                        {
                            TrickId = 5,
                            Description = "Trick 5 description",
                            DifficultyLevel = 3,
                            Name = "Trick5",
                            VideoUrl = "https://www.example.com/trick5"
                        });
                });

            modelBuilder.Entity("WakeProWebApi.Models.TrickSubStep", b =>
                {
                    b.Property<int>("TrickSubStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrickSubStepId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrickSubStepId");

                    b.ToTable("TrickSubSteps");

                    b.HasData(
                        new
                        {
                            TrickSubStepId = 1,
                            Description = "SubStep_1_description",
                            Name = "SubStep_1"
                        },
                        new
                        {
                            TrickSubStepId = 2,
                            Description = "SubStep_2_description",
                            Name = "SubStep_2"
                        },
                        new
                        {
                            TrickSubStepId = 3,
                            Description = "SubStep_3_description",
                            Name = "SubStep_3"
                        },
                        new
                        {
                            TrickSubStepId = 4,
                            Description = "SubStep_4_description",
                            Name = "SubStep_4"
                        },
                        new
                        {
                            TrickSubStepId = 5,
                            Description = "SubStep_5_description",
                            Name = "SubStep_5"
                        });
                });

            modelBuilder.Entity("WakeProWebApi.Models.TrickSubstepMapping", b =>
                {
                    b.Property<int>("MappingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MappingId"));

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SubstepId")
                        .HasColumnType("int");

                    b.Property<int>("TrickId")
                        .HasColumnType("int");

                    b.HasKey("MappingId");

                    b.ToTable("TrickSubstepMappings");

                    b.HasData(
                        new
                        {
                            MappingId = 1,
                            Order = 0,
                            SubstepId = 1,
                            TrickId = 1
                        },
                        new
                        {
                            MappingId = 2,
                            Order = 1,
                            SubstepId = 2,
                            TrickId = 1
                        },
                        new
                        {
                            MappingId = 3,
                            Order = 2,
                            SubstepId = 3,
                            TrickId = 1
                        },
                        new
                        {
                            MappingId = 4,
                            Order = 3,
                            SubstepId = 4,
                            TrickId = 1
                        },
                        new
                        {
                            MappingId = 5,
                            Order = 4,
                            SubstepId = 5,
                            TrickId = 1
                        },
                        new
                        {
                            MappingId = 6,
                            Order = 0,
                            SubstepId = 1,
                            TrickId = 2
                        },
                        new
                        {
                            MappingId = 7,
                            Order = 1,
                            SubstepId = 2,
                            TrickId = 2
                        },
                        new
                        {
                            MappingId = 8,
                            Order = 2,
                            SubstepId = 3,
                            TrickId = 2
                        },
                        new
                        {
                            MappingId = 9,
                            Order = 3,
                            SubstepId = 4,
                            TrickId = 2
                        },
                        new
                        {
                            MappingId = 10,
                            Order = 4,
                            SubstepId = 5,
                            TrickId = 3
                        },
                        new
                        {
                            MappingId = 11,
                            Order = 0,
                            SubstepId = 1,
                            TrickId = 3
                        },
                        new
                        {
                            MappingId = 12,
                            Order = 1,
                            SubstepId = 2,
                            TrickId = 3
                        },
                        new
                        {
                            MappingId = 13,
                            Order = 2,
                            SubstepId = 3,
                            TrickId = 3
                        },
                        new
                        {
                            MappingId = 14,
                            Order = 3,
                            SubstepId = 4,
                            TrickId = 3
                        },
                        new
                        {
                            MappingId = 15,
                            Order = 4,
                            SubstepId = 5,
                            TrickId = 3
                        });
                });

            modelBuilder.Entity("WakeProWebApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "user1@example.com",
                            Password = "Password1",
                            UserName = "user1"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "user2@example.com",
                            Password = "Password2",
                            UserName = "user2"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "user3@example.com",
                            Password = "Password3",
                            UserName = "user3"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "user4@example.com",
                            Password = "Password4",
                            UserName = "user4"
                        },
                        new
                        {
                            UserId = 5,
                            Email = "user5@example.com",
                            Password = "Password5",
                            UserName = "user5"
                        });
                });

            modelBuilder.Entity("WakeProWebApi.Models.UserTrickProgress", b =>
                {
                    b.Property<int>("UserTrickProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTrickProgressId"));

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("TrickId")
                        .HasColumnType("int");

                    b.Property<int>("TrickSubStepId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserTrickProgressId");

                    b.ToTable("UserTrickProgresses");

                    b.HasData(
                        new
                        {
                            UserTrickProgressId = 1,
                            IsCompleted = true,
                            TrickId = 1,
                            TrickSubStepId = 1,
                            UserId = 1
                        },
                        new
                        {
                            UserTrickProgressId = 2,
                            IsCompleted = false,
                            TrickId = 2,
                            TrickSubStepId = 2,
                            UserId = 2
                        },
                        new
                        {
                            UserTrickProgressId = 3,
                            IsCompleted = false,
                            TrickId = 3,
                            TrickSubStepId = 3,
                            UserId = 3
                        },
                        new
                        {
                            UserTrickProgressId = 4,
                            IsCompleted = false,
                            TrickId = 4,
                            TrickSubStepId = 4,
                            UserId = 4
                        },
                        new
                        {
                            UserTrickProgressId = 5,
                            IsCompleted = false,
                            TrickId = 5,
                            TrickSubStepId = 5,
                            UserId = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
